language: php
dist: trusty

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: deps=no
#    - php: 7
#      env: deps=no
#    - php: 7
#      env: deps=high
#    - php: 7.1
#      env: deps=no
#    - php: 7.1
#      env: deps=high


cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer
    - $HOME/.local

before_script:
    - cat ~/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    - echo > ~/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    - cat ~/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini


## disable xdebug
#  - mkdir -p "$HOME/.php-cs-fixer"
#  - mkdir -p build/logs
#  - composer self-update
#  - if [ "$deps" = "no" ]; then composer --prefer-dist install --dev; fi;
#  - if [ "$deps" = "high" ]; then composer --prefer-source update --dev; fi;

script:
#  - ./vendor/bin/php-cs-fixer fix --dry-run --diff --verbose
## enable xdebug
#  - ./vendor/bin/codecept build
#  - ./vendor/bin/codecept run unit --coverage --coverage-xml
#  - travis_retry php ./vendor/bin/coveralls -v

after_success:
