language: php
dist: trusty

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: deps=no
    - php: 7
      env: deps=no
    - php: 7
      env: deps=high
    - php: 7.1
      env: deps=no
    - php: 7.1
      env: deps=high


cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer
    - $HOME/.local

before_script:
    ## backup and disable xdebug
#    - cp ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/.phpenv/versions/$(phpenv version-name)/xdebug.ini.bak
#    - echo > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
#    - phpenv rehash
#    - mkdir -p "$HOME/.php-cs-fixer"
#    - mkdir -p build/logs
#    - composer self-update
#    - if [ "$deps" = "no" ]; then composer --prefer-dist install; fi;
#    - if [ "$deps" = "high" ]; then composer --prefer-source update; fi;

script:
#    - ./vendor/bin/php-cs-fixer fix --dry-run --diff --verbose
#    ## enable xdebug
#    - mv ~/.phpenv/versions/$(phpenv version-name)/xdebug.ini.bak ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
#    - ./vendor/bin/codecept build
#    - ./vendor/bin/codecept run unit --coverage --coverage-xml
    - if [ $(phpenv version-name) == "7" ]; then echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PHP VERSION 7 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"; fi

after_success:
#    - php vendor/bin/codacycoverage clover tests/_output/coverage.xml
