language: php
sudo: required
dist: trusty

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7
    - php: 7.1

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer
    - $HOME/.local

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer show --platform
  - composer install --ignore-platform-reqs

script:
  ./vendor/bin/phpunit